### ISSUE TITLE
是否支持分布式部署？

### ISSUE THREAD

**Issue by yuynagforhacker** [staugur/IncetOps#1]
咱们这个项目我看基本上是基于本地部署模式的，有没有分布式部署的？

**Comment by staugur** [comment]
在我印象中，也没有使用本地的东西，多点部署应该问题不大，只不过这种运维的程序也没必要多点，我本人暂时也没测试过。

**Comment by yuynagforhacker** [comment]
还有之后几个参数我不太清楚怎么设定，相关SYSTEM和SSO对应的几个参数，SSO中的app_id和app_secret测试中是不是没有必要设定？使用默认就可以？passport指的是什么？

**Comment by staugur** [comment]
其实也可以先不用认证，测试中，可以将main.py以下部分
```
@app.before_request
def before_request():
    g.signin = verify_sessionId(request.cookies.get("sessionId"))
```
改成
```
@app.before_request
def before_request():
    g.signin = True
```

**Comment by yuynagforhacker** [comment]
那我在config.py中需要把整个SYSTEM全部注释掉吗？

**Comment by staugur** [comment]
不过在刷新页面会有个提示，`系统异常，请稍后再试，状态码：0，error`

**Comment by staugur** [comment]
> 那我在config.py中需要把整个SYSTEM全部注释掉吗？

不用管它

**Comment by yuynagforhacker** [comment]
好的，app_id和app_secret的配置我用默认的是否可行？这个应该不需要改吧其实

**Comment by staugur** [comment]
> 好的，app_id和app_secret的配置我用默认的是否可行？这个应该不需要改吧其实

这时候，SSO SYSTEM已经相当于没用了，本来目前的使用它们的地方就是认证

**Comment by yuynagforhacker** [comment]
好的，感谢

**Comment by yuynagforhacker** [comment]
server {
    listen       80;
    server_name test.com;
    location ~ ^\/static\/.*$ {
        root /opt/IncetOps/src/;
    }
    location / {
       proxy_pass http://127.0.0.1:16000;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

这个配置是正确的吗？启动之后nginx显示502，16000显示的
werkzeug.routing.BuildError
BuildError: Could not build url for endpoint 'IncetOps.Inception'. Did you mean 'static' instead?

**Comment by staugur** [comment]
在你的/opt/IncetOps/src/logs下看看所有日志内容

**Comment by yuynagforhacker** [comment]
咱们使用的是python什么版本？我使用的2.7.5报错
python main.py
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    plugin = PluginManager()
  File "/opt/IncetOps/src/libs/plugins.py", line 39, in __init__
    self.__scanPlugins()
  File "/opt/IncetOps/src/libs/plugins.py", line 94, in __scanPlugins
    self.__runPlugins(package)
  File "/opt/IncetOps/src/libs/plugins.py", line 102, in __runPlugins
    plugin = __import__("{0}.{1}".format("plugins", package), fromlist=["plugins", ])
  File "/opt/IncetOps/src/plugins/ssoclient/__init__.py", line 55, in <module>
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

**Comment by staugur** [comment]
config.py SSO段 sso_server，设置一个有效的url，py版本对的

**Comment by yuynagforhacker** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/IncetOps/src/views/FrontView.py", line 22, in index
    return redirect(url_for("IncetOps.Inception"))
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'IncetOps.Inception'. Did you mean 'static' instead?

**Comment by staugur** [comment]
在你的/opt/IncetOps/src/logs下看看所有日志内容

**Comment by staugur** [comment]
这个应该是你某些地方有错误，没加载成功，而目前的代码没有raise出异常就继续了

**Comment by staugur** [comment]
现在可以拉取最新代码试试看

**Comment by yuynagforhacker** [comment]
[root@localhost src]# python main.py 
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    plugin = PluginManager(app, logger=plugin_logger)
  File "/usr/lib64/python2.7/site-packages/flask_pluginkit/flask_pluginkit.py", line 130, in __init__
    self.init_app(app)
  File "/usr/lib64/python2.7/site-packages/flask_pluginkit/flask_pluginkit.py", line 134, in init_app
    self.__scanPlugins()
  File "/usr/lib64/python2.7/site-packages/flask_pluginkit/flask_pluginkit.py", line 214, in __scanPlugins
    raise PluginError("Load Plugin Error")
flask_pluginkit.exceptions.PluginError: Load Plugin Error

**Comment by staugur** [comment]
。。。

os.getenv函数你可以先了解下，配置有错误

**Comment by staugur** [comment]
直接改成
MYSQL = "mysql://127.0.0.1:3306:root:root:incetops?charset=&timezone="
REDIS = "redis://localhost:6379/0"

        "DefaultBackupDatabase": "mysql://127.0.0.1:3306:root:root:incetops?charset=&timezone="
        # 默认备份库地址

**Comment by staugur** [comment]
http://docs.saintic.com/743928    部署安装的文档
